
Output examples/demo.gif

Set Shell "zsh"
Set FontSize 11
Set Width 1000
Set Height 600
Set Padding 15
Set WindowBar Colorful

Type "nachrichten" Sleep 500ms
Hide
Ctrl+U
Type "./nachrichten" Enter
Show

Sleep 2s

Type j Sleep 200ms
Type j Sleep 200ms
Type j Sleep 200ms
Type l Sleep 500ms
Down@200ms 3
Sleep 500ms
Type f Sleep 1000ms
Type i Sleep 1500ms
Type f Sleep 500ms
Type i

Sleep 1s

Type q

