
Output media/demo.gif

Require nachrichten

Set Shell "zsh"
Set FontSize 11
Set Width 1000
Set Height 600
Set Padding 15
Set WindowBar Colorful

Set PlaybackSpeed 2.0

Type "nachrichten" Sleep 1000ms
Enter

Sleep 3s

Tab Sleep 2000ms
Tab Sleep 2000ms
Type j Sleep 2000ms
Type k Sleep 2000ms
Type l Sleep 1000ms
Down@500ms 10
Sleep 1000ms
Type f Sleep 2000ms
Type i Sleep 3000ms
Type d Sleep 3000ms
Type "2" Sleep 3000ms
Type f Sleep 2000ms

Type q

