
Output media/demo.gif

Require nachrichten

Set Shell "zsh"
Set FontSize 11
Set Width 1000
Set Height 600
Set Padding 15
Set WindowBar Colorful

Set PlaybackSpeed 2.0

Type "nachrichten" Sleep 1000ms
Enter

Sleep 4s

Type j Sleep 400ms
Type j Sleep 400ms
Type j Sleep 400ms
Type l Sleep 1000ms
Down@300ms 10
Sleep 1000ms
Type f Sleep 2000ms
Type i Sleep 3000ms
Type f Sleep 1000ms
Type i

Sleep 2s

Type q

