
# Global settings for the application
Settings:
  HideHelpOnStartup: true
  PreloadThumbnails: true
  SelectorWidth: 0.3

# Configuration of keybinds used in the application
Keys:
  Up:
    - k
    - up
  Down:
    - j
    - down
  Left:
    - h
    - left
  Right:
    - l
    - right
  Prev:
    - shift+tab
  Next:
    - tab
  Full:
    - f
  Start:
    - g
    - home
  End:
    - G
    - end
  Quit:
    - q
    - esc
    - ctrl+c
  ShowArticle:
    - a
  ShowThumbnail:
    - i
  ShowDetails:
    - d
  OpenArticle:
    - o
  OpenVideo:
    - v
  OpenShortNews:
    - s
  Help:
    - "?"

# Configuration of how to open specific resources
# Via the args it is possible to provide flags to the application
# the arg $ will be replaced by the url of the resource
Application:
  Image:
    Path: sxiv
    Args:
      - $
  Audio:
    Path: mpv
    Args:
      - $
  Video:
    Path: mpv
    Args:
      - $
  HTML:
    Path: qutebrowser
    Args:
      - $

# Configuration of the theming
# Currently only the configuration of colors is implemented
Theme:
  PrimaryColor:         "#EBDBB2"
  ShadedColor:          "#928374"
  HighlightColor:       "#458588"
  HighlightShadedColor: "#83A598"
  WarningColor:         "#FB4934"
  WarningShadedColor:   "#CC241D"
  ReaderHighlightColor: "#FABD2F"
  ReaderHeadingColor:   "#8EC07C"

