
# Global settings for the application
Settings:
  HideHelpOnStartup: true

# Configuration of how to open specific resources
# Via the args it is possible to provide flags to the application
# the arg $ will be replaced by the url of the resource
#
Application:
  Image:
    Path: sxiv
    Args:
      - $
  Audio:
    Path: mpv
    Args:
      - $
  Video:
    Path: mpv
    Args:
      - $
  HTML:
    Path: qutebrowser
    Args:
      - $

# Configuration of the theming
# Currently only the configuration of colors is implemented
Theme:
  PrimaryColor:         "#EBDBB2"
  ShadedColor:          "#928374"
  HighlightColor:       "#458588"
  HighlightShadedColor: "#83A598"
  WarningColor:         "#FB4934"
  WarningShadedColor:   "#CC241D"
  ReaderHighlightColor: "#FABD2F"
  ReaderHeadingColor:   "#8EC07C"

