
# Global settings for the application
Settings:
  HideHelpOnStartup: true

# Configuration of how to open specific resources
# Via the args it is possible to provide flags to the application
# the arg $ will be replaced by the url of the resource
#
Application:
  Image:
    Path: sxiv
    Args:
      - $
  Audio:
    Path: mpv
    Args:
      - $
  Video:
    Path: mpv
    Args:
      - $
  HTML:
    Path: qutebrowser
    Args:
      - $

# Configuration of the theming
# Currently only the configuration of colors is implemented
Theme:
  PrimaryColor: "#3636D1"
  SecondaryColor: "#F8F8F2"
  NormalTitleColor: "#DDDDDD"
  NormalDescColor: "#777777"
  SelectedPrimaryColor: "#AD58B4"
  SelectedSecondaryColor: "#EE6FF8"
  BreakingColor: "#FF0000"
  ReaderHighlightColor: "#FFB86C"
  ReaderHeadingColor: "#BD93F9"

